export const messages = {
    en: {
        PUBLIC: {
            TITLE: 'Baishan Cloud Dashboard',
            DELETE: 'Delete',
            CONFIRMED: 'Submit',
            CANCLE: 'Cancle',
            CLOSE: 'Close',
            BACK: 'Back',
            ACL: 'Permissions',
            RESET: 'Reset',
            COPY: 'Copy',
            LOADING: 'Loading...',
            LINK_CONVERSION: 'Link conversion'
        },
        LOGIN: {
            TITLE: 'LOGIN',
            EMAILL: 'email',
            EMAILL_ALERT: 'Please input your email',
            IS_EMAILL: 'The mailbox is malformed',
            KEY: 'password',
            KEY_ALERT: 'Please enter your password',
            VARIFY: 'Verifying ...',
            BUTTON_LOGIN: 'Login',
            LOGIN_FAILED: 'Login failed',
            VALIDATE_FAILED: 'Input validate failed',
            LOGIN_AGAIN: 'Need to login again',
            KEEP_EMAIL: 'Remember my email'
        },
        NAV: {
            DOC: 'Documentation',
            LOGOUT: 'Logout',
            CHANGE_PASSWORD: 'Change password',
            NEW_PASSWORD: 'New password',
            CHANGE_PASSWORD_FAILED: 'Change password failed',
            PASSWORD_CHECK: 'The password requires 6 charactors'
        },
        SIDEBAR: {
            BUCKET: 'My Storage',
            DASHBOARD: 'Dashboard',
            KEYCHAIN: 'Keychain',
            MACHINE: 'Machine',
            PARTITION: 'Partition'
        },
        STORAGE: {
            TABLE_BUCKET_NAME: 'Bucket name',
            TABLE_KEY: 'Key',
            TABLE_SIZE: 'Size',
            TABLE_UPDATE_TIME: 'Update Time',
            TABLE_ACTION: 'Actions',
            ADD_BUCKET: 'Add bucket',
            DELETE_BUCKET: 'Delete bucket',
            BUCKET_KEY: 'Please fill in the bucket name',
            FILE_MAN: 'File Management',
            UPLOAD_FILE: 'Upload file',
            CREATE_FOLDER: 'Create folder',
            DELETE_FOLDER: 'Delete folder',
            DOWNLOAD_FILES: 'Download files',
            DELETE_FILES: 'Delete files',
            PREVIEW: 'Preview',
            GET_URL: 'Get Link',
            NEED_NAME: 'Need Key',
            KEY_LIM_CHA: 'The letters begin and can not contain special characters',
            CHA_LEN_3: 'Requires 3 characters',
            CHA_LEN_63: 'Up to 63 characters',
            ACL_LIST: 'Get List',
            ACL_UPLOAD_DELETE: 'Upload/Delete',
            ACL_VIEW: 'View Permisson',
            ACL_EDIT: 'Edit Permisson',
            BUCKET_SETTING: 'Bucket Settings',
            ACL_USER_GROUP: 'Group',
            ACL_GROUP: 'Group',
            OBJECT_PERMISSIONS: 'Object Permissions',
            ACL_PERMISSIONS: 'ACL Permissions',
            ACL_USER: 'User',
            ADD_USER: 'Add User',
            DELETE_USER: 'Delete User',
            USER: 'User',
            ACL_GROUP_INFO: 'CWN-X has a set of predefined groups.Giving access to these groups will allow public access to the resource.',
            BUCKET_OBJECT_PERMISSIONS_INFO: 'READ permission allows grantee to list objects in a bucket;WRITE permission allows grantee to create, overwrite and delete any object in a bucket.',
            BUCKET_ACL_PERMISSIONS_INFO: 'READ permission allows grantee to read the bucekt ACLs;WRITE permission allows grantee to modify the bucket ACLs.',
            ACL_USER_INFO: 'You can grant permission to an Baishancloud user by the email address or the canonical user ID.',
            OBJECT_OBJECT_PERMISSIONS_INFO: 'READ permission allows grantee to read the object data and metadata.',
            OBJECT_ACL_PERMISSIONS_INFO: 'READ permission allows grantee to read the object ACLs;WRITE permission allows grantee to modify the object ACLs.',
            READ: 'Read',
            WRITE: 'Write',
            SAVE_PERMISSIONS: 'Save permissions changes',
            SEARCH_FILE: 'Search file',
            DELETE_CONFIRMED: 'Are you sure you want to delete [{fileName}] ？',
            DELETE_FILES_CONFIRMED: 'Are you sure you want to delete the selected files?',
            ADD_FOLDER: 'Add folder',
            FOLDER_PLACEHOLDER: 'Requires folder name',
            FOLDER_CHECKINFO: 'Requires 1 characters',
            NO_TITLE: 'no title',
            NO_FILE: 'No file',
            COPY_LINK_CONFIRM: 'Copy {selectedFileKey} link?',
            COPIED: 'Copied',
            ADD_BUCKET_SUCCESS: 'Add bucket success',
            ADD_BUCKET_CHECK: 'Requires 3 characters',
            ADD_BUCKET_PLACEHOLDER: 'Requires bucket name',
            ADD_FOLDER_SUCCESS: 'Create a folder successfully',
            ADD_FOLDER_FAILED: 'Create a folder failed',
            DELETE_FILES_SUCCESS: 'Delete file successfully',
            DELETE_FILES_FAILED: 'Delete file failed',
            GET_PERMISSION_FAILED: 'Get permission list fail',
            PERMISSION_EMPTY: 'Permission can not be empty',
            PERMISSION_SUCCESS: 'Permission changes successfully',
            PERMISSION_FAILED: 'Save permission changes failed',
            UPLOAD_FAILED: 'Upload {file.name} failed',
            INVALID_NEW_USER: 'Invalid new user',
            PIC_IDEN: 'adault content detection',
            POLOCY_SUCCESS: 'Detection changes successfully',
            POLOCY_FAILED: 'Detection changes failed',
            FOLDER_INFO: 'Click the checkbox on the folder',
            AUTHORIZATION: 'Authorization',
            FILE_LIST: 'File list',
            HOME_PAGE: 'Home page',
            PRE_PAGE: 'Previous page',
            FILE_PERMISSIONS: 'File permissions',
            DOWNLOAD_FILE: 'Download file',
            IMG_PREVIEW: 'Image preview',
            COPY_FILE_LINK: ' Copy file link',
            DELETE_FILE: 'Delete file',
            DOCUMENTATION: 'Documentation',
            GET_ADULT_FAILED: 'Get settings failed',
            ADULT_OPEN_INFO: 'Plese choose Bucket to store',
            DELETE_BUCKET_INFO: 'This bucket is a designated bucket to store yellow pictures for [{unionName}]. Please change the bucket or close the function first.',
            PIC_STYLE: 'Picture styles',
            CREATE_STYLE: 'Create style',
            EXPORT_STYLE: 'Export style',
            IMPORT_STYLE: 'Import style',
            BASIC_EDIT: 'Basic edit',
            ADV_EDIT: 'advanced edit',
            STYLE_NAME: 'Style name',
            STYLE_CROP: 'Zoom mode',
            CROP_FIT: 'Equal proportion',
            CROP_NONE: 'Original size',
            STYLE_EFFECT: 'Special effects',
            STYLE_SHARPEN: 'sharpen',
            STYLE_QUALITY: 'Quality',
            STYLE_FORMAT: 'Format',
            STYLE_WATERMARKER: 'Watermark',
            WATERMARKER_TYPE: 'Watermark type',
            TEXT_WATERMARKER: 'Text watermark',
            IMG_WATERMARKER: 'Image watermark',
            TEXT_CONTENT: 'Text content',
            TEXT_STYLE: 'Text styles',
            STROKE: 'Stroke',
            WATERMARKER_POSITION: 'Watermark position',
            PADDING_LEFT: 'Padding left',
            PADDING_TOP: 'Padding top',
            OPACITY: 'Opacity',

            TITLE: 'My Storage',
            FILE_UPLOAD_LIM: 'Click or drag the file here to upload.',
            FOLDER_KEY: 'Folder name',
            NEXT_PAGE: 'Next page'
        },
        DASHBOARD: {
            THIS_MONTH: 'this month',
            LAST_MONTH: 'last month',
            YESTERDAY: 'Yesterday',
            SEVEN_DAYS: 'Last 7 days',
            THIRTY_DAYS: 'Last 30 days',
            THIS_SEASON: 'this season',
            LAST_SEASON: 'last season',
            BANDWIDTH: 'Bandwidth',
            BANDWIDTH_PEAK: 'Bandwidth Peak',
            FLOW: 'Traffic',
            CAPACITY: 'Capacity',
            CAPACITY_ALL: 'Total capacity',
            UPLOAD_SPACE_ALL: 'Total upload traffic',
            DOWNLOAD_SPACE_ALL: 'Total download traffic',
            DOWNLOAD_COUNT_ALL: 'Total Downloads',
            UPLOAD_COUNT_ALL: 'Total Uploads',
            UPLOAD_ADD: 'Upload increment',
            REQUEST_GET: 'Through put',
            REQUEST_GET_AVERAGE: 'Average downloads',
            QUANTITY: 'File count',
            TIMES: 'times',
            CAPACITY_ALL_INFO: 'The bytes stored until the last selected date.',
            UPLOAD_SPACE_ALL_INFO: 'The bytes uploaded within selected date range.',
            DOWNLOAD_SPACE_ALL_INFO: 'The bytes downloaded traffic within selected date range.',
            DOWNLOAD_COUNT_ALL_INFO: 'The number of download requests within selected date range.',
            UPLOAD_COUNT_ALL_INFO: 'The number of upload requests within selected date range.',
            UPLOAD_SPACE: 'Upload traffic',
            DOWNLOAD_SPACE: 'Download traffic',
            DOWNLOAD_COUNT: 'Downloads',
            UPLOAD_COUNT: 'Uploads',
            CAPACITY_INFO: 'the used capacity on the previous day adds the net increase of the capacity within the selected day. ',
            UPLOAD_SPACE_INFO: 'Total bytes uploaded within a day',
            DOWNLOAD_SPACE_INFO: 'Total bytes downloaded within a day',
            DOWNLOAD_COUNT_INFO: 'The number of download requests within a day',
            UPLOAD_COUNT_INFO: 'The number of upload and delete requests within a day',
            UNIT: 'unit',
            GET_BUCKET_FAILED: 'Get bucket list fail'
        },
        i: {
            select: {
                placeholder: 'Select',
                noMatch: 'No matching data'
            },
            table: {
                noDataText: 'No Data',
                noFilteredDataText: 'No filter data',
                confirmFilter: 'Confirm',
                resetFilter: 'Reset',
                clearFilter: 'All'
            },
            datepicker: {
                selectDate: 'Select date',
                selectTime: 'Select time',
                startTime: 'Start Time',
                endTime: 'End Time',
                clear: 'Clear',
                ok: 'OK',
                month: '',
                month1: 'January',
                month2: 'February',
                month3: 'March',
                month4: 'April',
                month5: 'May',
                month6: 'June',
                month7: 'July',
                month8: 'August',
                month9: 'September',
                month10: 'October',
                month11: 'November',
                month12: 'December',
                year: '',
                weeks: {
                    sun: 'Sun',
                    mon: 'Mon',
                    tue: 'Tue',
                    wed: 'Wed',
                    thu: 'Thu',
                    fri: 'Fri',
                    sat: 'Sat'
                },
                months: {
                    m1: 'Jan',
                    m2: 'Feb',
                    m3: 'Mar',
                    m4: 'Apr',
                    m5: 'May',
                    m6: 'Jun',
                    m7: 'Jul',
                    m8: 'Aug',
                    m9: 'Sep',
                    m10: 'Oct',
                    m11: 'Nov',
                    m12: 'Dec'
                }
            },
            transfer: {
                titles: {
                    source: 'Source',
                    target: 'Target'
                },
                filterPlaceholder: 'Search here',
                notFoundText: 'Not Found'
            },
            modal: {
                okText: 'OK',
                cancelText: 'Cancel'
            },
            poptip: {
                okText: 'OK',
                cancelText: 'Cancel'
            },
            page: {
                prev: 'Previous Page',
                next: 'Next Page',
                total: 'Total',
                item: 'item',
                items: 'items',
                prev5: 'Previous 5 Pages',
                next5: 'Next 5 Pages',
                page: '/page',
                goto: 'Goto',
                p: ''
            },
            rate: {
                star: 'Star',
                stars: 'Stars'
            },
            tree: {
                emptyText: 'No Data'
            }
        }
    },
    cn: {
        PUBLIC: {
            TITLE: '白山云存储',
            CONFIRMED: '确定',
            CANCLE: '取消',
            CLOSE: '关闭',
            DELETE: '删除',
            BACK: '后退',
            ACL: '权限控制',
            RESET: '重置',
            COPY: '复制',
            LOADING: '加载中...',
            LINK_CONVERSION: 'url转换'
        },
        LOGIN: {
            TITLE: '登 录',
            EMAILL: '邮箱地址',
            EMAILL_ALERT: '请输入邮箱',
            IS_EMAILL: '邮箱格式错误',
            KEY: '密码',
            KEY_ALERT: '请输入密码',
            VARIFY: '正在验证 ...',
            BUTTON_LOGIN: '登 录',
            LOGIN_FAILED: '登录失败',
            VALIDATE_FAILED: '验证失败',
            LOGIN_AGAIN: '请重新登录',
            KEEP_EMAIL: '记住邮箱'
        },
        NAV: {
            DOC: '帮助文档',
            LOGOUT: '退出登录',
            CHANGE_PASSWORD: '修改密码',
            NEW_PASSWORD: '新密码',
            CHANGE_PASSWORD_FAILED: '修改密码失败',
            PASSWORD_CHECK: '密码不能少于6个字符'
        },
        SIDEBAR: {
            BUCKET: '我的存储',
            DASHBOARD: '统计分析',
            KEYCHAIN: '密钥管理',
            MACHINE: '机器信息',
            PARTITION: '磁盘分区'
        },
        STORAGE: {
            TABLE_BUCKET_NAME: '空间名',
            TABLE_KEY: '文件名',
            TABLE_UPDATE_TIME: '更新时间',
            TABLE_SIZE: '占用空间',
            TABLE_ACTION: '操作',
            ADD_BUCKET: '新建 Bucket',
            DELETE_BUCKET: '删除 Bucket',
            BUCKET_KEY: '请填写Bucket名称',
            FILE_MAN: '文件管理',
            UPLOAD_FILE: '上传文件',
            CREATE_FOLDER: '创建文件夹',
            DELETE_FOLDER: '删除文件夹',
            DOWNLOAD_FILES: '下载文件',
            DELETE_FILES: '删除文件',
            PREVIEW: '预览',
            GET_URL: '获取地址',
            NEED_NAME: '名称必填',
            KEY_LIM_CHA: '字母开头且不能包含特殊字符',
            CHA_LEN_3: '最少3个字符',
            CHA_LEN_63: '最多63个字符',
            ACL_LIST: '获取列表',
            ACL_UPLOAD_DELETE: '上传/删除',
            ACL_VIEW: '查看权限',
            ACL_EDIT: '编辑权限',
            BUCKET_SETTING: '空间设置',
            ACL_USER_GROUP: '用户组权限',
            ACL_GROUP: '用户组',
            OBJECT_PERMISSIONS: '对象访问',
            ACL_PERMISSIONS: '权限访问',
            ACL_USER: '用户权限',
            ADD_USER: '添加用户',
            DELETE_USER: '删除用户',
            USER: '用户',
            ACL_GROUP_INFO: '白山云存储拥有一系列预定义的组。向这些组授予访问许可将允许资源被公开访问',
            BUCKET_OBJECT_PERMISSIONS_INFO: '“读取”允许被授权者列出存储桶中的对象;“写入”允许被授权者创建、覆盖和删除存储桶中的任意对象',
            BUCKET_ACL_PERMISSIONS_INFO: '“读取”允许被授权者读取存储桶ACL;“写入”允许被授权者为适用的存储桶编写ACL',
            ACL_USER_INFO: '您可以通过电子邮件地址或规范用户ID将许可授予白山云用户',
            OBJECT_OBJECT_PERMISSIONS_INFO: '“读取”允许被授权者读取对象数据及其元数据',
            OBJECT_ACL_PERMISSIONS_INFO: '“读取”允许被授权者读取对象ACL。“写入”允许被授权者为适用的对象编写ACL',
            READ: '读取',
            WRITE: '写入',
            SAVE_PERMISSIONS: '确认修改',
            SEARCH_FILE: '查找文件',
            DELETE_CONFIRMED: '确定要删除 [{fileName}] 吗？',
            DELETE_FILES_CONFIRMED: '确定删除选中的文件吗？',
            ADD_FOLDER: '创建文件夹',
            FOLDER_PLACEHOLDER: '文件夹名称',
            FOLDER_CHECKINFO: '文件夹名称不可少于一个字符',
            NO_TITLE: '无标题',
            NO_FILE: '文件夹／Bucket为空',
            COPY_LINK_CONFIRM: '确定复制 {selectedFileKey} 的链接吗?',
            COPIED: '复制成功',
            ADD_BUCKET_SUCCESS: '创建成功',
            ADD_BUCKET_CHECK: 'Bucket名称不可少于3个字符',
            ADD_BUCKET_PLACEHOLDER: 'Bucket名称',
            ADD_FOLDER_SUCCESS: '创建成功',
            ADD_FOLDER_FAILED: '创建失败',
            DELETE_FILES_SUCCESS: '删除成功',
            DELETE_FILES_FAILED: '删除失败',
            GET_PERMISSION_FAILED: '获取列表失败',
            PERMISSION_EMPTY: '权限不能为空',
            PERMISSION_SUCCESS: '修改成功',
            PERMISSION_FAILED: '修改失败',
            UPLOAD_FAILED: '{file.name} 上传失败',
            INVALID_NEW_USER: '不合法的新用户',
            PIC_IDEN: '图片鉴黄',
            POLOCY_SUCCESS: '设置成功',
            POLOCY_FAILED: '设置失败',
            FOLDER_INFO: '单击选中文件夹',
            AUTHORIZATION: '授权',
            FILE_LIST: '文件列表',
            HOME_PAGE: '首页',
            PRE_PAGE: '上一页',
            FILE_PERMISSIONS: '权限设置',
            DOWNLOAD_FILE: '下载文件',
            IMG_PREVIEW: '图片预览',
            COPY_FILE_LINK: '复制链接',
            DELETE_FILE: '删除文件',
            DOCUMENTATION: '帮助文档',
            GET_ADULT_FAILED: '获取鉴黄设置失败',
            ADULT_OPEN_INFO: '请选择黄图存放Bucket',
            DELETE_BUCKET_INFO: '[{fileName}]是[{unionName}]指定的黄图存放Bucket，请先更改[{unionName}]的黄图存放Bucket或关闭图片鉴黄功能',
            PIC_STYLE: '图片处理',
            CREATE_STYLE: '创建样式',
            EXPORT_STYLE: '导出样式',
            IMPORT_STYLE: '导入样式',
            BASIC_EDIT: '基础编辑',
            ADV_EDIT: '高级编辑',
            STYLE_NAME: '样式名称',
            STYLE_CROP: '缩放方式',
            CROP_FIT: '等比例缩放',
            CROP_NONE: '保持原尺寸不变',
            STYLE_EFFECT: '图片处理',
            STYLE_SHARPEN: '图片锐化',
            STYLE_QUALITY: '图片质量',
            STYLE_FORMAT: '保存格式',
            STYLE_WATERMARKER: '是否添加水印',
            WATERMARKER_TYPE: '水印类型',
            TEXT_WATERMARKER: '文字水印',
            IMG_WATERMARKER: '图片水印',
            TEXT_CONTENT: '文字内容',
            TEXT_STYLE: '文字样式',
            STROKE: '描边',
            WATERMARKER_POSITION: '水印位置',
            PADDING_LEFT: '左边距离',
            PADDING_TOP: '顶边距离',
            OPACITY: '不透明度',

            TITLE: '我的存储',
            FILE_UPLOAD_LIM: '点击或拖拽上传',
            FOLDER_KEY: 'Folder 名称',
            NEXT_PAGE: '下一页'
        },
        DASHBOARD: {
            THIS_MONTH: '本月',
            LAST_MONTH: '上月',
            YESTERDAY: '昨天',
            SEVEN_DAYS: '近7天',
            THIRTY_DAYS: '近30天',
            THIS_SEASON: '本季度',
            LAST_SEASON: '上季度',
            BANDWIDTH: '带宽',
            BANDWIDTH_PEAK: '带宽峰值',
            FLOW: '流量',
            CAPACITY_ALL: '总存储容量',
            UPLOAD_SPACE_ALL: '总上传流量',
            DOWNLOAD_SPACE_ALL: '总下载流量',
            DOWNLOAD_COUNT_ALL: '总读请求数',
            UPLOAD_COUNT_ALL: '总写请求数',
            UPLOAD_ADD: '上传增量',
            REQUEST_GET: '请求次数',
            REQUEST_GET_AVERAGE: '平均下载次数',
            QUANTITY: '文件数',
            TIMES: '次',
            CAPACITY_ALL_INFO: '截止到所选时间区间最后一天的存储容量',
            UPLOAD_SPACE_ALL_INFO: '所选时间区间内每天的上传流量之和',
            DOWNLOAD_SPACE_ALL_INFO: '所选时间区间内每天的下载流量之和',
            DOWNLOAD_COUNT_ALL_INFO: '所选时间区间内每天的读请求数之和',
            UPLOAD_COUNT_ALL_INFO: '所选时间区间内每天的写请求数之和',
            CAPACITY: '存储容量',
            UPLOAD_SPACE: '上传流量',
            DOWNLOAD_SPACE: '下载流量',
            DOWNLOAD_COUNT: '读请求数',
            UPLOAD_COUNT: '写请求数',
            CAPACITY_INFO: '某天的存储容量=前一天的存储容量+该日的增量-该日的删除容量',
            UPLOAD_SPACE_INFO: '某天的上传流量',
            DOWNLOAD_SPACE_INFO: '某天的下载流量',
            DOWNLOAD_COUNT_INFO: '某天的读请求数',
            UPLOAD_COUNT_INFO: '某天的写请求数',
            GET_BUCKET_FAILED: '获取Bucket列表失败'
        },
        i: {
            select: {
                placeholder: '请选择',
                noMatch: '无匹配数据'
            },
            table: {
                noDataText: '暂无数据',
                noFilteredDataText: '暂无筛选结果',
                confirmFilter: '筛选',
                resetFilter: '重置',
                clearFilter: '全部'
            },
            datepicker: {
                selectDate: '选择日期',
                selectTime: '选择时间',
                startTime: '开始时间',
                endTime: '结束时间',
                clear: '清空',
                ok: '确定',
                month: '月',
                month1: '1 月',
                month2: '2 月',
                month3: '3 月',
                month4: '4 月',
                month5: '5 月',
                month6: '6 月',
                month7: '7 月',
                month8: '8 月',
                month9: '9 月',
                month10: '10 月',
                month11: '11 月',
                month12: '12 月',
                year: '年',
                weeks: {
                    sun: '日',
                    mon: '一',
                    tue: '二',
                    wed: '三',
                    thu: '四',
                    fri: '五',
                    sat: '六'
                },
                months: {
                    m1: '1月',
                    m2: '2月',
                    m3: '3月',
                    m4: '4月',
                    m5: '5月',
                    m6: '6月',
                    m7: '7月',
                    m8: '8月',
                    m9: '9月',
                    m10: '10月',
                    m11: '11月',
                    m12: '12月'
                }
            },
            transfer: {
                titles: {
                    source: '源列表',
                    target: '目的列表'
                },
                filterPlaceholder: '请输入搜索内容',
                notFoundText: '列表为空'
            },
            modal: {
                okText: '确定',
                cancelText: '取消'
            },
            poptip: {
                okText: '确定',
                cancelText: '取消'
            },
            page: {
                prev: '上一页',
                next: '下一页',
                total: '共',
                item: '条',
                items: '条',
                prev5: '向前 5 页',
                next5: '向后 5 页',
                page: '条/页',
                goto: '跳至',
                p: '页'
            },
            rate: {
                star: '星',
                stars: '星'
            },
            tree: {
                emptyText: '暂无数据'
            }
        }
    }
}
