export const messages = {
    en: {
        PUBLIC: {
            TITLE: 'Baishan Cloud Dashboard',
            DELETE: 'Delete',
            CONFIRMED: 'Submit',
            CANCLE: 'Cancle',
            CLOSE: 'Close',
            BACK: 'Back',
            ACL: 'Permissions',
            RESET: 'Reset',
            COPY: 'Copy',
            LOADING: 'Loading...',
            LINK_CONVERSION: 'Link conversion',
            EDIT: 'Edit'
        },
        LOGIN: {
            TITLE: 'LOGIN',
            EMAILL: 'email',
            EMAILL_ALERT: 'Please input your email',
            IS_EMAILL: 'The mailbox is malformed',
            KEY: 'password',
            KEY_ALERT: 'Please enter your password',
            VARIFY: 'Verifying ...',
            BUTTON_LOGIN: 'Login',
            LOGIN_FAILED: 'Login failed',
            VALIDATE_FAILED: 'Input validate failed',
            LOGIN_AGAIN: 'Need to login again',
            KEEP_EMAIL: 'Remember my email',
            USER_MANAGE: 'User management'
        },
        NAV: {
            DOC: 'Documentation',
            LOGOUT: 'Logout',
            RESELECT_USER: 'Switch user',
            CHANGE_PASSWORD: 'Change password',
            NEW_PASSWORD: 'New password',
            CHANGE_PASSWORD_FAILED: 'Change password failed',
            PASSWORD_CHECK: 'The password requires 6 charactors'
        },
        SIDEBAR: {
            BUCKET: 'My Storage',
            DASHBOARD: 'Dashboard',
            KEYCHAIN: 'Keychain',
            VIDEO: 'Video',
            MACHINE: 'Machine',
            PARTITION: 'Partition',
            USER: 'User Management',
            TEMPLATE: 'Template',
            OUTPUT: 'Output',
            PIPELINE: 'Pipeline',
            JOB: 'Job'
        },
        KEYCHAIN: {
            ADD_KEY: 'Add accesskey',
            COPY_ACCESSKEY: 'Click to copy accesskey',
            COPY_SECRETKEY: 'Click to copy secretkey',
            DELETE_KEY: 'Delete keychain',
            DELETE_KEY_COM: 'Are you sure you want to delete [{accesskey}] ？'
        },
        STORAGE: {
            TABLE_BUCKET_NAME: 'Bucket name',
            TABLE_KEY: 'Key',
            TABLE_SIZE: 'Size',
            TABLE_UPDATE_TIME: 'Update Time',
            TABLE_ACTION: 'Actions',
            ADD_BUCKET: 'Add bucket',
            DELETE_BUCKET: 'Delete bucket',
            BUCKET_KEY: 'Please fill in the bucket name',
            FILE_MAN: 'File Management',
            UPLOAD_FILE: 'Upload file',
            CREATE_FOLDER: 'Create folder',
            DELETE_FOLDER: 'Delete folder',
            DOWNLOAD_FILES: 'Download files',
            DELETE_FILES: 'Delete files',
            PREVIEW: 'Preview',
            GET_URL: 'Get Link',
            NEED_NAME: 'Need Key',
            KEY_LIM_CHA: 'The letters begin and can not contain special characters',
            CHA_LEN_3: 'Requires 3 characters',
            CHA_LEN_63: 'Up to 63 characters',
            ACL_LIST: 'Get List',
            ACL_UPLOAD_DELETE: 'Upload/Delete',
            ACL_VIEW: 'View Permisson',
            ACL_EDIT: 'Edit Permisson',
            BUCKET_SETTING: 'Bucket Settings',
            ACL_USER_GROUP: 'Group',
            ACL_GROUP: 'Group',
            OBJECT_PERMISSIONS: 'Object Permissions',
            ACL_PERMISSIONS: 'ACL Permissions',
            ACL_USER: 'User',
            ADD_USER: 'Add User',
            DELETE_USER: 'Delete User',
            USER: 'User',
            ACL_GROUP_INFO: 'CWN-X has a set of predefined groups.Giving access to these groups will allow public access to the resource.',
            BUCKET_OBJECT_PERMISSIONS_INFO: 'READ permission allows grantee to list objects in a bucket;WRITE permission allows grantee to create, overwrite and delete any object in a bucket.',
            BUCKET_ACL_PERMISSIONS_INFO: 'READ permission allows grantee to read the bucekt ACLs;WRITE permission allows grantee to modify the bucket ACLs.',
            ACL_USER_INFO: 'You can grant permission to an Baishancloud user by the email address or the canonical user ID.',
            OBJECT_OBJECT_PERMISSIONS_INFO: 'READ permission allows grantee to read the object data and metadata.',
            OBJECT_ACL_PERMISSIONS_INFO: 'READ permission allows grantee to read the object ACLs;WRITE permission allows grantee to modify the object ACLs.',
            READ: 'Read',
            WRITE: 'Write',
            SAVE_PERMISSIONS: 'Save permissions changes',
            SEARCH_FILE: 'Search file',
            DELETE_CONFIRMED: 'Are you sure you want to delete [{fileName}] ？',
            UNBIND_CONFIRMED: 'Are you sure you want to unbind [{fileName}] ？',
            DELETE_FILES_CONFIRMED: 'Are you sure you want to delete the selected files?',
            ADD_FOLDER: 'Add folder',
            FOLDER_PLACEHOLDER: 'Requires folder name',
            FOLDER_CHECKINFO: 'Requires 1 characters',
            RENAME: 'File rename',
            RENAME_PLACEHOLDER: 'Requires new file name',
            RENAME_CHECKINFO: 'Requires 1 characters',
            NO_TITLE: 'no title',
            NO_FILE: 'No file',
            COPY_LINK_CONFIRM: 'Copy {selectedFileKey} link?',
            COPIED: 'Copied',
            ADD_BUCKET_SUCCESS: 'Add bucket success',
            ADD_BUCKET_CHECK: 'Requires 3 characters',
            ADD_BUCKET_PLACEHOLDER: 'Requires bucket name',
            ADD_FOLDER_SUCCESS: 'Create a folder successfully',
            ADD_FOLDER_FAILED: 'Create a folder failed',
            DELETE_FILES_SUCCESS: 'Delete file [{fileName}] successfully',
            DELETE_FILES_FAILED: 'Delete file [{fileName}] failed',
            GET_PERMISSION_FAILED: 'Get permission list fail',
            PERMISSION_EMPTY: 'Permission can not be empty',
            PERMISSION_SUCCESS: 'Permission changes successfully',
            PERMISSION_FAILED: 'Save permission changes failed',
            UPLOAD_FAILED: 'Upload {fileName} failed',
            INVALID_NEW_USER: 'Invalid new user',
            PIC_IDEN: 'adault content detection',
            CORS_CONFIG: 'CORS Configuration',
            RULES_AT_MOST: '{rulesNumber}/100 rules at most',
            ADD_RULE: 'Add Rule',
            ENTER_KEY: 'You can set multiple，each ended up with the "Enter" key',
            ALLOWED_ORIGINS_CANNOT_EMPTY: 'The "Allowed Origins" cannot be empty !',
            ALLOWED_METHODS_CANNOT_EMPTY: 'The "Allowed Methods" cannot be empty !',
            CACHE_TIME_BE_NUMBER: 'The "Max Age Seconds" must be number !',
            SET_SUCCESS: 'Set successfully',
            DELETE_SUCCESS: 'Delete successfully',
            DELETE_CORS_CONFIRMED: 'Are you sure you want to delete [this cors rule] ?',
            POLOCY_SUCCESS: 'Detection changes successfully',
            POLOCY_FAILED: 'Detection changes failed',
            FOLDER_INFO: 'Click the folder first',
            AUTHORIZATION: 'Authorization',
            FILE_LIST: 'File list',
            HOME_PAGE: 'Home page',
            PRE_PAGE: 'Previous page',
            FILE_PERMISSIONS: 'File permissions',
            DOWNLOAD_FILE: 'Download file',
            IMG_PREVIEW: 'Image preview',
            COPY_FILE_LINK: ' Copy file link',
            DELETE_FILE: 'Delete file',
            DOCUMENTATION: 'Documentation',
            GET_ADULT_FAILED: 'Get settings failed',
            ADULT_OPEN_INFO: 'Plese choose Bucket to store',
            DELETE_BUCKET_INFO: 'This bucket is a designated bucket to store yellow pictures for [{unionName}]. Please change the bucket or close the function first.',
            PIC_STYLE: 'Picture styles',
            CREATE_STYLE: 'Create style',
            EXPORT_STYLE: 'Export style',
            IMPORT_STYLE: 'Import style',
            BASIC_EDIT: 'Basic edit',
            ADV_EDIT: 'advanced edit',
            STYLE_NAME: 'Name',
            STYLE_CROP: 'Process',
            CROP_FIT: 'Equal proportion',
            CROP_NONE: 'Original size',
            STYLE_EFFECT: 'Special effects',
            STYLE_SHARPEN: 'sharpen',
            STYLE_QUALITY: 'Quality',
            STYLE_FORMAT: 'Format',
            STYLE_WATERMARKER: 'Watermark',
            WATERMARKER_TYPE: 'Type',
            TEXT_WATERMARKER: 'Text watermark',
            IMG_WATERMARKER: 'Image watermark',
            TEXT_CONTENT: 'Content',
            TEXT_STYLE: 'Text styles',
            STROKE: 'Stroke',
            WATERMARKER_POSITION: 'Position',
            PADDING_LEFT: 'Left',
            PADDING_TOP: 'Top',
            OPACITY: 'Opacity',
            WATERMARKER_PIC: 'Watermark picture',
            FIT_STYLE: 'Fit style',
            FIT_WIDTH: 'Width',
            FIT_HEIGHT: 'Height',
            NO_STYLE: 'No style',
            DELETE_STYLE: 'Delete style',
            DELETE_STYLE_SUCCESS: 'Delete style successfully',
            DELETE_STYLE_FAILED: 'Delete style failed',
            ADD_STYLE_SUCCESS: 'Create a style successfully',
            ADD_STYLE_FAILED: 'Create a style failed',
            EDIT: 'Edit',
            RULE_PREVIEW: 'Processing preview',
            PROSCESS_PARAM: 'Parameter',
            CROP: 'Crop',
            CROP_SCALE: 'scale',
            CROP_FILL: 'fill',
            CROP_PAD: 'pad',
            CROP_CROP: 'crop',
            CROP_THUMB: 'thumb',
            RULENAME_INFO: 'Uses numbers, lowercase letters, underscores, no more than 20 characters',
            SELECT_LOCATION: 'Location',
            PIXEL: 'Pixel',
            PERCENT: 'Percent',
            MORE_SET: 'More settings',
            FLIP_MODE: 'Flip mode',
            ANGLE: 'Angle',
            FILTER_EFFECTS: 'Filters/effects:',
            FILTER_EFFECTS_NONE: 'None',
            GRAYSCALE: 'Gray scale',
            AUTO_CONTRAST: 'Auto contrast',
            BRIGHTNESS: 'Brightness',
            NEGATE: 'Negate',
            SHARPEN: 'Sharpen',
            BLUR: 'Blur',
            OIL_PAINT: 'Oil painting',
            PIXELATE: 'Pixelate',
            ADD_COLOR: 'Add color',
            IMPROVE: 'Auto',
            BRIGHTNESS_VALUE: 'value',
            BLUR_VALUE: 'value',
            SHARPEN_VALUE: 'value',
            OIL_VALUE: 'value',
            COLOR: 'Color',
            COLOR_VALUE: 'value',
            PX_VALUE: 'value',
            BORDER: 'Border',
            ON: 'ON',
            OFF: 'OFF',
            BORDER_SET: 'Border',
            RADIUS: 'Radius',
            TEXT_CONTENT_INFO: 'Please enter the watermark text content',
            BACKGROUBD: 'Background',
            PARA_DESC: 'Description,',
            SEE_COCUMENT: 'See document',
            RULE_NAME_EXISTS: 'Rule name already exists!',
            SAVE_FAILED: 'Save failed',
            NO_MORE_4: 'Instruction entries must not exceed 4 items',
            WATER_PNG_VALID_INFO: 'Supports the PNG file called ASCII characters except “/:,-”',
            PIC_EXAMPLE: 'Sample (crop + watermark)',
            SENIOR_INFO: 'Before using the senior editor, recommended to read Imgx image processing service instructions',
            PIC_UPLOAD_INFO: 'Only JSON files',
            GET_RULES_FAILED: 'Get rule list failed',
            FORMAT_ORIGINAL: 'Original',
            RULE_NAME: 'Rule name',
            PICTURE_STYLES: 'Picture styles',
            PICTURE_QUALITY: 'Quality',
            PICTURE_FORMAT: 'Format',
            OPERATE: 'Operate',
            ISOPEN: 'Open:',
            OPEN: 'Open',
            CLOSE: 'Close',
            ADULT_SAVE: 'Save:',
            ADULT_SAVE_TIPS: 'If you do not have the Bucket for storing the Yellow pictures , you need to start with',
            ADULT_CREATE_BUCKET: 'Create one',
            ADULT_RULE: 'Process:',
            ADULT_RULE_SAVE: 'Keep the yellow picture in the original Bucket and copy it into the store Bucket',
            ADULT_RULE_DEL: 'Delete the yellow picture in the original Bucket and copy it into the store Bucket',
            CROP_LPAD: 'Pad narrow',
            CROP_MPAD: 'Pad enlarge',
            CROP_LFILL: 'Fill narrow',
            CROP_FACE: 'Face',
            CROP_FACES: 'Faces',
            CROP_FACE_CENTER: 'Face center',
            CROP_FACES_CENTER: 'Faces center',
            CROP_MFIT: 'Fit enlarge',
            CROP_LFIT: 'Fit narrow',
            ANGLE_ROTATION: 'Rotation angle',
            ANGLE_VFLIP: 'Vertical',
            ANGLE_HFLIP: 'Horizontal',
            GRAVITY_NORTH_WEST: 'north_west',
            GRAVITY_NORTH: 'north',
            GRAVITY_NORTH_EAST: 'north_east',
            GRAVITY_WEST: 'west',
            GRAVITY_CENTER: 'Center',
            GRAVITY_EAST: 'East',
            GRAVITY_SOUTH_WEST: 'south_west',
            GRAVITY_SOUTH: 'South',
            GRAVITY_SOUTH_EAST: 'south_east',
            GRAVITY_NOGRAVITY: 'Specify coordinate points',
            GRAVITY_XY_CENTER: 'Designated center point',
            SEPIA: 'sepia',
            RED: 'red',
            GREEN: 'green',
            BLUE: 'blue',
            YELLOW: 'yellow',
            CYAN: 'cyan',
            MAGENTA: 'magenta',
            NO_LIST: 'No data',
            GET_DATA_ERROR: 'Get data error',
            COLOR_ERROR: 'Invalid color value',

            TITLE: 'My Storage',
            FILE_UPLOAD_LIM: 'Click or drag the file here to upload.',
            FOLDER_KEY: 'Folder name',
            NEXT_PAGE: 'Next page'
        },
        DASHBOARD: {
            THIS_MONTH: 'this month',
            LAST_MONTH: 'last month',
            YESTERDAY: 'Yesterday',
            SEVEN_DAYS: 'Last 7 days',
            THIRTY_DAYS: 'Last 30 days',
            THIS_SEASON: 'this season',
            LAST_SEASON: 'last season',
            BANDWIDTH: 'Bandwidth',
            BANDWIDTH_PEAK: 'Bandwidth Peak',
            FLOW: 'Traffic',
            CAPACITY: 'Capacity',
            CAPACITY_ALL: 'Total capacity',
            UPLOAD_SPACE_ALL: 'Total upload traffic',
            DOWNLOAD_SPACE_ALL: 'Total download traffic',
            DOWNLOAD_COUNT_ALL: 'Total Downloads',
            UPLOAD_COUNT_ALL: 'Total Uploads',
            UPLOAD_ADD: 'Upload increment',
            REQUEST_GET: 'Through put',
            REQUEST_GET_AVERAGE: 'Average downloads',
            QUANTITY: 'File count',
            TIMES: 'times',
            CAPACITY_ALL_INFO: 'The bytes stored until the last selected date.',
            UPLOAD_SPACE_ALL_INFO: 'The bytes uploaded within selected date range.',
            DOWNLOAD_SPACE_ALL_INFO: 'The bytes downloaded traffic within selected date range.',
            DOWNLOAD_COUNT_ALL_INFO: 'The number of download requests within selected date range.',
            UPLOAD_COUNT_ALL_INFO: 'The number of upload requests within selected date range.',
            UPLOAD_SPACE: 'Upload traffic',
            DOWNLOAD_SPACE: 'Download traffic',
            DOWNLOAD_COUNT: 'Downloads',
            UPLOAD_COUNT: 'Uploads',
            DELETE_COUNT: 'Deletes',
            DELETE_SPACE: 'Delete Space',
            CAPACITY_INFO: 'the used capacity on the previous day adds the net increase of the capacity within the selected day. ',
            UPLOAD_SPACE_INFO: 'Total bytes uploaded within a day',
            DOWNLOAD_SPACE_INFO: 'Total bytes downloaded within a day',
            DOWNLOAD_COUNT_INFO: 'The number of download requests within a day',
            UPLOAD_COUNT_INFO: 'The number of upload and delete requests within a day',
            UNIT: 'unit',
            GET_BUCKET_FAILED: 'Get bucket list fail',
            EXPORT_DATA: 'Export data'
        },
        USER: {
            CREATE_SUB_USER: 'Create user',
            CREATE_USER: 'Create user',
            BIND_USER: 'Bind user',
            NO_USER: 'No user',
            BASE_INFO: 'Base information',
            USER_NAME: 'User name',
            EMAILL: 'Email',
            PASSWORD: 'Password',
            COMPANY: 'Company',
            PERMISSON_MANAGE: 'Permissions',
            BUCKET_NAME: 'Bucket name',
            BUCKET_PERMISSON: 'Bucket permisson',
            FILE_PERMISSON: 'File permisson',
            READ: 'Read',
            WRITE: 'Write',
            REQUIRE_USER_NAME: 'Requires user name',
            REQUIRE_COMPANY: 'Requires company name',
            GENERAL_USER: 'General user',
            SUB_USER: 'Sub user',
            ADMIN: 'Administrator',
            SUPER_USER: 'Super user',
            CREATE_SUCCESS: 'Create user success',
            CREATE_INFO: 'Input validate failed',
            CREATE_SUB_SUCCESS: 'Create sub user success',
            CREATE_SUB_ERROR: 'Create sub user error',
            UPDATE_SUB_SUCCESS: 'Update sub user success',
            UPDATE_SUB_ERROR: 'Update sub user error',
            USER_TYPE: 'User type'
        },
        VIDEO: {
            NEW_TEMPLATE: 'New template',
            ENCODING: 'Encoding',
            CODING_PROFILE: 'Coding profile',
            CODING_LEVEL: 'Coding level',
            CODING_QUALITY: 'Coding quality',
            FIXED_KEY_FRAME_SPACING: 'Fixed key frame spacing',
            SAMPLE_RATE: 'Sample rate',
            BIT_RATE: 'Bit rate',
            FRAME_RATE: 'Frame rate',
            RESOLUTION: 'Resolution',
            ASPECT_RATIO: 'Aspect ratio',
            WIDTH: 'Width',
            HEIGHT: 'Height',
            CHANNELS: 'Channels',
            DELETED_SUCCESSFULLY: 'Deleted successfully!',
            FAILED_TO_DELETE: 'Failed to delete!',
            TEMPLATE_CONFIGURATION: 'Template configuration',
            TEMPLATE_NAME: 'Template name',
            TEMPLATE_NAME_CHAR_NUMBER: 'Not less than 1 character, and not more than 20 characters',
            TEMPLATE_NAME_WARING: 'Invalid template name',
            TEMPLATE_DESCRIPTION_WARING: 'Invalid description',
            TEMPLATE_DESCRIPTION: 'Description',
            TEMPLATE_DESCRIPTION_CHAR_NUMBER: 'Not more than 100 characters',
            ENTER_THE_TEMPLATE_DESCRIPTION_TEXT: 'Enter the template description text',
            PACKAGE_FORMAT: 'Package format',
            ON: 'On',
            OFF: 'Off',
            VIDEO_PARAMETER_CONFIGURATION: 'Video parameter configuration',
            AUDIO_PARAMETER_CONFIGURATION: 'Audio parameter configuration',
            ADAPTIVE: 'Adaptive',
            USER_DEFINED: 'User-defined',
            UNALTERED: 'Unaltered',
            SAVE: 'Save',
            CREATED_SUCCESSFULLY: 'Created successfully',
            NEW_CONFIGURATION: 'New configuration',
            TRANSCODING_TEMPLATE: 'Transcoding template',
            VIDEO_TRANSCODING_TEMPLATE_ID: 'Video transcoding template ID',
            HLS_SLICE_LENGTH: 'HLS Slice length',
            HLS_SLICE_LENGTH_CANNOT_BE_0: 'HLS Slice length can not be 0',
            OPEN: 'Open',
            CLOSE: 'Close',
            WHETHER_TO_OPEN: 'Whether to open',
            SET_UP_SUCCESSFULLY: 'Set up successfully!',
            SET_UP_FAILED: 'Set up failed!',
            AUTOMATIC_TRANSCODING_CONFIGURATION: 'Automatic transcoding configuration',
            INPUT_CONFIGURATION: 'Input configuration',
            OUTPUT_CONFIGURATION: 'Output configuration',
            TRANSCODING_PATH_RULES: 'Transcoding path rules',
            BY_FILE_EXTENSION_CONFIGURATION: 'By file extension name',
            REGULAR_EXPRESSION_CONFIGURATION: 'By regular expression',
            PATH: 'Path',
            EXTENSION_NAME: 'Extension name',
            REGULAR_EXPRESSION: 'Regular expression',
            SEPARATE_EXTENSION_NAMES: '(Separate extension names by using "|")',
            EXPRESSION_INCORRECT: 'The expression is incorrect',
            INPUT_BUCKET: 'Input bucket',
            OUTPUT_BUCKET: 'Output bucket',
            OUTPUT_KEY_PREFIX: 'Output file key prefix',
            OUTPUT_RULES: 'Output rules',
            VIDEO_SCREENSHOTS_RULES: 'Video screenshots rules',
            AT_LEAST_ONE_RULE: 'There is at least one between the output rule and the video screenshots rule',
            ADD: 'Add',
            MORE_CONFIGURATION: 'More configuration',
            YES: 'Yes',
            NO: 'No',
            WHETHER_DELETE_ORIGINAL_FILE_AFTER_TRANSCODING: 'Delete the original file',
            WHETHER_RETAIN_ORIGINAL_PATH_AFTER_TRANSCODING: 'Retain the original path',
            PERMISSION_SETTINGS: 'Permission settings',
            USER_GROUP_PERMISSIONS: 'User group permissions',
            USER_PERMISSIONS: 'User permissions',
            OUTPUT_FILE_NAME_SUFFIX: 'File name suffix',
            SCREENSHOT_START_TIME: 'Start time',
            SCREENSHOT_START_TIME_SECOND: 'Start time (s)',
            SCREENSHOT_INTERVAL: 'Interval',
            SCREENSHOT_INTERVAL_SECOND: 'Interval (s)',
            SCREENSHOT_MAX_NUMBER: 'Max number',
            SCREENSHOT_RESOLUTION: 'Resolution',
            OK: 'OK',
            CANCEL: 'Cancel',
            FORMAT: 'Format',
            SLICE_FORMAT: 'Slice format',
            TRANSCODING_SUCCESSFUL_CALLBACK_URL: 'Successful, callback url',
            TRANSCODING_FAILED_CALLBACK_URL: 'Failed, callback url',
            FILE_NAME_SUFFIX_CANNOT_EMPTY: 'The file name suffix can not be empty',
            MASTER_PLAYLIST_CONFIGURATION: 'MasterPlaylist configuration',
            MASTER_PLAYLIST_FILE_NAME_SUFFIX: 'MasterPlaylist file name suffix',
            AUTO_OUTPUT_RULES_DESCRIPTION: 'After setting the auto transcoding, at least one of the template output is TS in the output rules, and all the HLS slice length need to be consistent and can not be 0',
            ADAPTIVE_EXIST_TS_FORMAT: 'When setting the adaptive transcoding, the TS format item of the transcoding template needs to exist in the output rules',
            ADAPTIVE_HLS_SLICE_LENGTH_CONSISTENT: 'When setting the adaptive transcoding, the HLS slice length needs to be consistent in the output rules',
            ADAPTIVE_HLS_SLICE_LENGTH_CANNOT_BE_0: 'When setting the adaptive transcoding, the HLS slice length can not be 0 in the output rules',
            SECOND: 'second',
            NEW_PIPELINE: 'New pipeline',
            PIPELINE_MANAGEMENT: 'Pipeline management',
            PIPELINE_NAME: 'Pipeline name',
            PIPELINE_NAME_INFO: 'Please enter the pipeline name',
            PIPELINE_NAME_CANNOT_EMPTY: 'The pipeline name cannot be empty',
            PIPELINE_NAME_CHAR_NUMBER: 'Please not more than 40 characters',
            UPDATED_SUCCESSFULLY: 'Updated successfully',
            PIPELINE_ID: 'Pileline ID',
            ACCEPT_JOB_SUCCESS_CALLBACK_URL: 'Success callback url',
            ACCEPT_JOB_FAILURE_CALLBACK_URL: 'Failure callback url',
            ACCEPT_JOB_SUCCESS_CALLBACK_URL_INFO: 'Please enter the callback url accepting job successfully',
            ACCEPT_JOB_FAILURE_CALLBACK_URL_INFO: 'Please enter the callback url accepting job failed',
            ENTER_CORRECT_PIPELINE_NAME: 'Please enter the correct pipeline name',
            STATUS: 'Status',
            ACTIONS: 'Actions',
            NO_DATA: 'No data',
            SNAPSHOTS_RULES: 'Snapshots Rules',
            OUTPUT_FILE_NAME: 'Output file name',
            MP_NAME_INFO: 'File name can not be empty',
            OUTPUT_TABLE_INFO: 'At last one poutput rule',
            CREATED: 'Created',
            DELETED: 'Delete successfully',
            PIPE: 'Pipeline',
            CREATE_JOB: 'Create',
            JOB_ID: 'ID',
            PIPE_ID: 'Pipeline ID',
            JOB_TEMPLATE: 'Template ID',
            CREATE_TIME: ' Create time',
            OPERATION: 'Actions',
            JOB_CONF: 'Job configuration',
            JOB_CREATE: 'Create',
            BASIC_SET: 'Basic',
            JOB_PIPE: 'Pipeline',
            SRC_FILE: 'Source file',
            SEARCH_INFO: 'Please use search when file number is greater than 50 (prefix match)',
            HLS_FILE_NAME: 'HLS file name',
            SRC_FILE_INFO: 'Please select the input source file',
            KEYS_REG: 'Keys Regex',
            OUTPUTS: 'Outputs',
            CONTAINER: 'Container',
            VIDEO: 'Video',
            AUDIO: 'Audio',
            TEMPLATE_NAME_TABLE: 'Name',
            CONF: 'Configuration',
            WH_UNALTERED: 'Calculate by resolution',
            OUTPUTKEY_REQUIRED: 'Output file name is required',
            SHOTKEY_REQUIRED: 'File name suffix is required',
            OUTPUTEMPLATE_REQUIRED: 'Transcoding template is required',
            OUTPUTKEY_SUFFIX_REQUIRED: 'File name suffixis required',
            REG_ERROR: 'Invalid regular expression',
            MP_NAME_ERROR: 'Invalid MasterPlaylist file name suffix',
            TEMPLATE_DELETED_ERROR: 'The preset is currently being used',
            JOB_CANCEL_ERROR: 'The job is progressing',
            PIPELINE_DELETE_ERROR: 'Delete failed: the pipeline is being used',
            BASE_INFO: 'Basic information',
            HLS_REQUIRED: 'HLS file name is required'
        },
        i: {
            select: {
                placeholder: 'Select',
                noMatch: 'No matching data'
            },
            table: {
                noDataText: 'No Data',
                noFilteredDataText: 'No filter data',
                confirmFilter: 'Confirm',
                resetFilter: 'Reset',
                clearFilter: 'All'
            },
            datepicker: {
                selectDate: 'Select date',
                selectTime: 'Select time',
                startTime: 'Start Time',
                endTime: 'End Time',
                clear: 'Clear',
                ok: 'OK',
                month: '',
                month1: 'January',
                month2: 'February',
                month3: 'March',
                month4: 'April',
                month5: 'May',
                month6: 'June',
                month7: 'July',
                month8: 'August',
                month9: 'September',
                month10: 'October',
                month11: 'November',
                month12: 'December',
                year: '',
                weeks: {
                    sun: 'Sun',
                    mon: 'Mon',
                    tue: 'Tue',
                    wed: 'Wed',
                    thu: 'Thu',
                    fri: 'Fri',
                    sat: 'Sat'
                },
                months: {
                    m1: 'Jan',
                    m2: 'Feb',
                    m3: 'Mar',
                    m4: 'Apr',
                    m5: 'May',
                    m6: 'Jun',
                    m7: 'Jul',
                    m8: 'Aug',
                    m9: 'Sep',
                    m10: 'Oct',
                    m11: 'Nov',
                    m12: 'Dec'
                }
            },
            transfer: {
                titles: {
                    source: 'Source',
                    target: 'Target'
                },
                filterPlaceholder: 'Search here',
                notFoundText: 'Not Found'
            },
            modal: {
                okText: 'OK',
                cancelText: 'Cancel'
            },
            poptip: {
                okText: 'OK',
                cancelText: 'Cancel'
            },
            page: {
                prev: 'Previous Page',
                next: 'Next Page',
                total: 'Total',
                item: 'item',
                items: 'items',
                prev5: 'Previous 5 Pages',
                next5: 'Next 5 Pages',
                page: '/page',
                goto: 'Goto',
                p: ''
            },
            rate: {
                star: 'Star',
                stars: 'Stars'
            },
            tree: {
                emptyText: 'No Data'
            }
        }
    },
    cn: {
        PUBLIC: {
            TITLE: '白山云存储',
            CONFIRMED: '确定',
            CANCLE: '取消',
            CLOSE: '关闭',
            DELETE: '删除',
            BACK: '后退',
            ACL: '权限控制',
            RESET: '重置',
            COPY: '复制',
            LOADING: '加载中...',
            LINK_CONVERSION: 'url转换',
            EDIT: '编辑'
        },
        LOGIN: {
            TITLE: '登 录',
            EMAILL: '邮箱地址',
            EMAILL_ALERT: '请输入邮箱',
            IS_EMAILL: '邮箱格式错误',
            KEY: '密码',
            KEY_ALERT: '请输入密码',
            VARIFY: '正在验证 ...',
            BUTTON_LOGIN: '登 录',
            LOGIN_FAILED: '登录失败',
            VALIDATE_FAILED: '验证失败',
            LOGIN_AGAIN: '请重新登录',
            KEEP_EMAIL: '记住邮箱',
            USER_MANAGE: '用户管理'
        },
        NAV: {
            DOC: '帮助文档',
            LOGOUT: '退出登录',
            RESELECT_USER: '切换关联账号',
            CHANGE_PASSWORD: '修改密码',
            NEW_PASSWORD: '新密码',
            CHANGE_PASSWORD_FAILED: '修改密码失败',
            PASSWORD_CHECK: '密码不能少于6个字符'
        },
        KEYCHAIN: {
            ADD_KEY: '新增密钥',
            COPY_ACCESSKEY: '点击复制 accesskey',
            COPY_SECRETKEY: '点击复制 secretkey',
            DELETE_KEY: '删除密钥',
            DELETE_KEY_COM: '确定删除 [{accesskey}] ？'
        },
        SIDEBAR: {
            BUCKET: '我的存储',
            DASHBOARD: '统计分析',
            KEYCHAIN: '密钥管理',
            VIDEO: '视频处理',
            MACHINE: '机器信息',
            PARTITION: '磁盘分区',
            USER: '用户管理',
            TEMPLATE: '转码模版',
            OUTPUT: '自动转码配置',
            PIPELINE: '管道管理',
            JOB: '任务管理'
        },
        STORAGE: {
            TABLE_BUCKET_NAME: '空间名',
            TABLE_KEY: '文件名',
            TABLE_UPDATE_TIME: '更新时间',
            TABLE_SIZE: '占用空间',
            TABLE_ACTION: '操作',
            ADD_BUCKET: '新建 Bucket',
            DELETE_BUCKET: '删除 Bucket',
            BUCKET_KEY: '请填写Bucket名称',
            FILE_MAN: '文件管理',
            UPLOAD_FILE: '上传文件',
            CREATE_FOLDER: '创建文件夹',
            DELETE_FOLDER: '删除文件夹',
            DOWNLOAD_FILES: '下载文件',
            DELETE_FILES: '删除文件',
            PREVIEW: '预览',
            GET_URL: '获取地址',
            NEED_NAME: '名称必填',
            KEY_LIM_CHA: '字母开头且不能包含特殊字符',
            CHA_LEN_3: '最少3个字符',
            CHA_LEN_63: '最多63个字符',
            ACL_LIST: '获取列表',
            ACL_UPLOAD_DELETE: '上传/删除',
            ACL_VIEW: '查看权限',
            ACL_EDIT: '编辑权限',
            BUCKET_SETTING: '空间设置',
            ACL_USER_GROUP: '用户组权限',
            ACL_GROUP: '用户组',
            OBJECT_PERMISSIONS: '对象访问',
            ACL_PERMISSIONS: '权限访问',
            ACL_USER: '用户权限',
            ADD_USER: '添加用户',
            DELETE_USER: '删除用户',
            USER: '用户',
            ACL_GROUP_INFO: '白山云存储拥有一系列预定义的组。向这些组授予访问许可将允许资源被公开访问',
            BUCKET_OBJECT_PERMISSIONS_INFO: '“读取”允许被授权者列出存储桶中的对象;“写入”允许被授权者创建、覆盖和删除存储桶中的任意对象',
            BUCKET_ACL_PERMISSIONS_INFO: '“读取”允许被授权者读取存储桶ACL;“写入”允许被授权者为适用的存储桶编写ACL',
            ACL_USER_INFO: '您可以通过电子邮件地址或规范用户ID将许可授予白山云用户',
            OBJECT_OBJECT_PERMISSIONS_INFO: '“读取”允许被授权者读取对象数据及其元数据',
            OBJECT_ACL_PERMISSIONS_INFO: '“读取”允许被授权者读取对象ACL。“写入”允许被授权者为适用的对象编写ACL',
            READ: '读取',
            WRITE: '写入',
            SAVE_PERMISSIONS: '确认修改',
            SEARCH_FILE: '查找文件',
            DELETE_CONFIRMED: '确定要删除 [{fileName}] 吗？',
            UNBIND_CONFIRMED: '确定要解绑 [{fileName}] 吗？',
            DELETE_FILES_CONFIRMED: '确定删除选中的文件吗？',
            ADD_FOLDER: '创建文件夹',
            FOLDER_PLACEHOLDER: '文件夹名称',
            FOLDER_CHECKINFO: '文件夹名称不可少于一个字符',
            NO_TITLE: '无标题',
            NO_FILE: '文件夹／Bucket为空',
            COPY_LINK_CONFIRM: '确定复制 {selectedFileKey} 的链接吗?',
            COPIED: '复制成功',
            ADD_BUCKET_SUCCESS: '创建成功',
            ADD_BUCKET_CHECK: 'Bucket名称不可少于3个字符',
            ADD_BUCKET_PLACEHOLDER: 'Bucket名称',
            RENAME: '文件重命名',
            RENAME_PLACEHOLDER: '新文件名',
            RENAME_CHECKINFO: '至少需要一个字符',
            ADD_FOLDER_SUCCESS: '创建成功',
            ADD_FOLDER_FAILED: '创建失败',
            DELETE_FILES_SUCCESS: '删除成功',
            DELETE_FILES_FAILED: '删除失败',
            GET_PERMISSION_FAILED: '获取列表失败',
            PERMISSION_EMPTY: '权限不能为空',
            PERMISSION_SUCCESS: '修改成功',
            PERMISSION_FAILED: '修改失败',
            UPLOAD_FAILED: '{fileName} 上传失败',
            INVALID_NEW_USER: '不合法的新用户',
            PIC_IDEN: '图片鉴黄',
            CORS_CONFIG: 'CORS跨域配置',
            RULES_AT_MOST: '已有{rulesNumber}条/最多100条',
            ADD_RULE: '创建规则',
            ENTER_KEY: '可以设置多个，每个都以"回车键"结束',
            ALLOWED_ORIGINS_CANNOT_EMPTY: '"Allowed Origins"不能为空！',
            ALLOWED_METHODS_CANNOT_EMPTY: '"Allowed Methods"不能为空！',
            CACHE_TIME_BE_NUMBER: '"Max Age Seconds"必须为数字！',
            SET_SUCCESS: '设置成功',
            DELETE_SUCCESS: '删除成功',
            DELETE_CORS_CONFIRMED: '确定要删除[这条CORS规则]吗？',
            POLOCY_SUCCESS: '设置成功',
            POLOCY_FAILED: '设置失败',
            FOLDER_INFO: '需先点击文件夹',
            AUTHORIZATION: '授权',
            FILE_LIST: '文件列表',
            HOME_PAGE: '首页',
            PRE_PAGE: '上一页',
            FILE_PERMISSIONS: '权限设置',
            DOWNLOAD_FILE: '下载文件',
            IMG_PREVIEW: '图片预览',
            COPY_FILE_LINK: '复制链接',
            DELETE_FILE: '删除文件',
            DOCUMENTATION: '帮助文档',
            GET_ADULT_FAILED: '获取鉴黄设置失败',
            ADULT_OPEN_INFO: '请选择黄图存放Bucket',
            DELETE_BUCKET_INFO: '[{fileName}]是[{unionName}]指定的黄图存放Bucket，请先更改[{unionName}]的黄图存放Bucket或关闭图片鉴黄功能',
            PIC_STYLE: '图片处理',
            CREATE_STYLE: '创建样式',
            EXPORT_STYLE: '导出样式',
            IMPORT_STYLE: '导入样式',
            BASIC_EDIT: '基础编辑',
            ADV_EDIT: '高级编辑',
            STYLE_NAME: '样式名称',
            STYLE_CROP: '处理方式',
            CROP_FIT: '等比例缩放',
            CROP_NONE: '保持原尺寸不变',
            STYLE_EFFECT: '图片处理',
            STYLE_SHARPEN: '图片锐化',
            STYLE_QUALITY: '图片质量',
            STYLE_FORMAT: '保存格式',
            STYLE_WATERMARKER: '添加水印',
            WATERMARKER_TYPE: '水印类型',
            TEXT_WATERMARKER: '文字水印',
            IMG_WATERMARKER: '图片水印',
            TEXT_CONTENT: '文字内容',
            TEXT_STYLE: '文字样式',
            STROKE: '描边',
            WATERMARKER_POSITION: '水印位置',
            PADDING_LEFT: '左边距离',
            PADDING_TOP: '顶边距离',
            OPACITY: '不透明度',
            WATERMARKER_PIC: '水印图片',
            FIT_STYLE: '缩略宽高',
            FIT_WIDTH: '缩略宽度',
            FIT_HEIGHT: '缩略高度',
            NO_STYLE: '没有已定义的样式',
            DELETE_STYLE: '删除样式',
            DELETE_STYLE_SUCCESS: '删除成功',
            DELETE_STYLE_FAILED: '删除失败',
            ADD_STYLE_SUCCESS: '创建成功',
            ADD_STYLE_FAILED: '创建失败',
            EDIT: '编辑',
            RULE_PREVIEW: '处理预览',
            PROSCESS_PARAM: '处理参数',
            CROP: '裁剪',
            CROP_SCALE: '固定宽高缩放',
            CROP_FILL: '等比例裁剪',
            CROP_PAD: '背景填充等比例缩放',
            CROP_CROP: '指定尺寸位置裁剪',
            CROP_THUMB: '定位人脸裁剪',
            RULENAME_INFO: '名称使用数字、小写字母、下划线，不超过20个字符',
            SELECT_LOCATION: '选择位置',
            PIXEL: '像素',
            PERCENT: '百分比',
            MORE_SET: '更多设置',
            FLIP_MODE: '翻转模式',
            ANGLE: '角度',
            FILTER_EFFECTS: '滤镜与特效:',
            FILTER_EFFECTS_NONE: '原图',
            GRAYSCALE: '灰度',
            AUTO_CONTRAST: '自动对比度',
            BRIGHTNESS: '亮度',
            NEGATE: '反色',
            SHARPEN: '锐化',
            BLUR: '模糊',
            OIL_PAINT: '油画',
            PIXELATE: '像素化',
            ADD_COLOR: '增加颜色',
            IMPROVE: '自动',
            BRIGHTNESS_VALUE: '图片亮度',
            BLUR_VALUE: '模糊值',
            SHARPEN_VALUE: '锐化值',
            OIL_VALUE: '油画值',
            COLOR: '颜色',
            COLOR_VALUE: '颜色取值',
            PX_VALUE: '像素值',
            BORDER: '设置边框',
            ON: '开',
            OFF: '关',
            BORDER_SET: '边框设置',
            RADIUS: '生成圆角',
            TEXT_CONTENT_INFO: '请输入水印文字内容',
            BACKGROUBD: '背景',
            PARA_DESC: '参数说明，',
            SEE_COCUMENT: '见文档',
            RULE_NAME_EXISTS: '规则名已存在！',
            SAVE_FAILED: '保存失败',
            NO_MORE_4: '指令条目不能超过4条',
            WATER_PNG_VALID_INFO: '支持png格式文件，文件名为不包含“/:,-”的ascii字符',
            PIC_EXAMPLE: '示例（图片缩放+图片水印）',
            SENIOR_INFO: '使用高级编辑之前，建议先阅读Imgx图片处理服务使用说明',
            PIC_UPLOAD_INFO: '只支持json文件',
            GET_RULES_FAILED: '获取列表失败',
            FORMAT_ORIGINAL: '原图格式',
            RULE_NAME: '规则名',
            PICTURE_STYLES: '图片样式',
            PICTURE_QUALITY: '图片质量',
            PICTURE_FORMAT: '图片格式',
            OPERATE: '操作',
            ISOPEN: '是否开启：',
            OPEN: '开启',
            CLOSE: '关闭',
            ADULT_SAVE: '黄图存放：',
            ADULT_SAVE_TIPS: '如果没有专门存放鉴别后黄图的Bucket，您需要先',
            ADULT_CREATE_BUCKET: '创建一个Bucket',
            ADULT_RULE: '处理规则：',
            ADULT_RULE_SAVE: '保留原Bucket里的黄图并复制到黄图存放Bucket',
            ADULT_RULE_DEL: '删除原Bucket里的黄图并复制到黄图存放Bucket',
            CROP_LPAD: '背景填充等比例缩小',
            CROP_MPAD: '背景填充等比例放大',
            CROP_LFILL: '不放大原图的等比例裁剪',
            CROP_FACE: '定位一张最易识别的人脸',
            CROP_FACES: '定位多张人脸',
            CROP_FACE_CENTER: '定位一张人脸，若无人脸定位到原图中心',
            CROP_FACES_CENTER: '定位多张人脸，若无人脸定位到原图中心',
            CROP_MFIT: '等比例放大',
            CROP_LFIT: '等比例缩小',
            ANGLE_ROTATION: '旋转角度',
            ANGLE_VFLIP: '垂直翻转',
            ANGLE_HFLIP: '水平翻转',
            GRAVITY_NORTH_WEST: '左上位置',
            GRAVITY_NORTH: '正上位置，水平方向居中',
            GRAVITY_NORTH_EAST: '右上位置',
            GRAVITY_WEST: '左边，垂直方向居中',
            GRAVITY_CENTER: '正中',
            GRAVITY_EAST: '右边，垂直方向居中',
            GRAVITY_SOUTH_WEST: '左下位置',
            GRAVITY_SOUTH: '正下位置',
            GRAVITY_SOUTH_EAST: '右下位置',
            GRAVITY_NOGRAVITY: '指定起点坐标',
            GRAVITY_XY_CENTER: '指定的xy为中心点',
            SEPIA: '褐色',
            RED: '红色',
            GREEN: '绿色',
            BLUE: '蓝色',
            YELLOW: '黄色',
            CYAN: '青色',
            MAGENTA: '粉色',
            NO_LIST: '列表为空',
            GET_DATA_ERROR: '获取数据失败',
            COLOR_ERROR: '颜色值不合法',

            TITLE: '我的存储',
            FILE_UPLOAD_LIM: '点击或拖拽上传',
            FOLDER_KEY: 'Folder 名称',
            NEXT_PAGE: '下一页'
        },
        DASHBOARD: {
            THIS_MONTH: '本月',
            LAST_MONTH: '上月',
            YESTERDAY: '昨天',
            SEVEN_DAYS: '近7天',
            THIRTY_DAYS: '近30天',
            THIS_SEASON: '本季度',
            LAST_SEASON: '上季度',
            BANDWIDTH: '带宽',
            BANDWIDTH_PEAK: '带宽峰值',
            FLOW: '流量',
            CAPACITY_ALL: '总存储容量',
            UPLOAD_SPACE_ALL: '总上传流量',
            DOWNLOAD_SPACE_ALL: '总下载流量',
            DOWNLOAD_COUNT_ALL: '总读请求数',
            UPLOAD_COUNT_ALL: '总写请求数',
            UPLOAD_ADD: '上传增量',
            REQUEST_GET: '请求次数',
            REQUEST_GET_AVERAGE: '平均下载次数',
            QUANTITY: '文件数',
            TIMES: '次',
            CAPACITY_ALL_INFO: '截止到所选时间区间最后一天的存储容量',
            UPLOAD_SPACE_ALL_INFO: '所选时间区间内每天的上传流量之和',
            DOWNLOAD_SPACE_ALL_INFO: '所选时间区间内每天的下载流量之和',
            DOWNLOAD_COUNT_ALL_INFO: '所选时间区间内每天的读请求数之和',
            UPLOAD_COUNT_ALL_INFO: '所选时间区间内每天的写请求数之和',
            CAPACITY: '存储容量',
            UPLOAD_SPACE: '上传流量',
            DOWNLOAD_SPACE: '下载流量',
            DOWNLOAD_COUNT: '读取请求',
            UPLOAD_COUNT: '写入请求',
            DELETE_COUNT: '删除请求',
            DELETE_SPACE: '删除容量',
            CAPACITY_INFO: '某天的存储容量=前一天的存储容量+该日的增量-该日的删除容量',
            UPLOAD_SPACE_INFO: '某天的上传流量',
            DOWNLOAD_SPACE_INFO: '某天的下载流量',
            DOWNLOAD_COUNT_INFO: '某天的读请求数',
            UPLOAD_COUNT_INFO: '某天的写请求数',
            GET_BUCKET_FAILED: '获取Bucket列表失败',
            EXPORT_DATA: '导出数据'
        },
        USER: {
            CREATE_SUB_USER: '新建账号',
            CREATE_USER: '新建帐号',
            BIND_USER: '绑定账号',
            NO_USER: '没有用户',
            BASE_INFO: '基本信息',
            USER_NAME: '用户名',
            EMAILL: '邮箱',
            PASSWORD: '密码',
            COMPANY: '公司名',
            PERMISSON_MANAGE: '权限管理',
            BUCKET_NAME: '桶',
            BUCKET_PERMISSON: '桶权限',
            FILE_PERMISSON: '文件权限',
            READ: '读',
            WRITE: '写',
            REQUIRE_USER_NAME: '请填写用户名',
            REQUIRE_COMPANY: '请填写公司名',
            GENERAL_USER: '普通账号',
            SUB_USER: '子账号',
            ADMIN: '管理员',
            SUPER_USER: '超级账号',
            CREATE_SUCCESS: '创建成功',
            CREATE_INFO: '验证失败',
            CREATE_SUB_SUCCESS: '子账号创建成功',
            CREATE_SUB_ERROR: '子账号创建失败',
            UPDATE_SUB_SUCCESS: '子账号更新成功',
            UPDATE_SUB_ERROR: '子账号更新失败',
            USER_TYPE: '账号类型'
        },
        VIDEO: {
            NEW_TEMPLATE: '新建模板',
            ENCODING: '编码方式',
            CODING_PROFILE: '编码Profile',
            CODING_LEVEL: '编码Level',
            CODING_QUALITY: '编码质量',
            FIXED_KEY_FRAME_SPACING: '固定关键帧间距',
            SAMPLE_RATE: '采样率',
            BIT_RATE: '码率',
            FRAME_RATE: '帧率',
            RESOLUTION: '分辨率',
            ASPECT_RATIO: '宽高比',
            WIDTH: '宽度',
            HEIGHT: '高度',
            CHANNELS: '声道数',
            DELETED_SUCCESSFULLY: '删除成功！',
            FAILED_TO_DELETE: '删除失败！',
            TEMPLATE_CONFIGURATION: '模板配置',
            TEMPLATE_NAME: '模板名称',
            TEMPLATE_NAME_CHAR_NUMBER: '不少于1个字符，不超过20个字符',
            TEMPLATE_NAME_WARING: '模版名称无效',
            TEMPLATE_DESCRIPTION_WARING: '描述信息无效',
            TEMPLATE_DESCRIPTION: '模板描述',
            TEMPLATE_DESCRIPTION_CHAR_NUMBER: '不超过100个字符',
            ENTER_THE_TEMPLATE_DESCRIPTION_TEXT: '输入模板描述文字',
            PACKAGE_FORMAT: '输出封装格式',
            ON: '开',
            OFF: '关',
            VIDEO_PARAMETER_CONFIGURATION: '视频参数配置',
            AUDIO_PARAMETER_CONFIGURATION: '音频参数配置',
            ADAPTIVE: '自适应',
            USER_DEFINED: '自定义',
            UNALTERED: '不变',
            SAVE: '保存',
            CREATED_SUCCESSFULLY: '创建成功',
            NEW_CONFIGURATION: '新建配置',
            TRANSCODING_TEMPLATE: '转码模板',
            VIDEO_TRANSCODING_TEMPLATE_ID: '视频转码模板ID',
            HLS_SLICE_LENGTH: 'HLS切片时长',
            HLS_SLICE_LENGTH_CANNOT_BE_0: 'HLS切片时长不能为0',
            OPEN: '开启',
            CLOSE: '关闭',
            WHETHER_TO_OPEN: '是否开启',
            SET_UP_SUCCESSFULLY: '设置成功！',
            SET_UP_FAILED: '设置失败！',
            AUTOMATIC_TRANSCODING_CONFIGURATION: '自动转码配置',
            INPUT_CONFIGURATION: '输入配置',
            OUTPUT_CONFIGURATION: '输出配置',
            TRANSCODING_PATH_RULES: '允许转码的路径规则',
            BY_FILE_EXTENSION_CONFIGURATION: '按文件扩展名配置',
            REGULAR_EXPRESSION_CONFIGURATION: '正则表达式配置',
            PATH: '路径',
            EXTENSION_NAME: '扩展名',
            REGULAR_EXPRESSION: '正则表达式',
            SEPARATE_EXTENSION_NAMES: '(多个扩展名使用“|”分割)',
            EXPRESSION_INCORRECT: '表达式错误',
            INPUT_BUCKET: '输入Bucket',
            OUTPUT_BUCKET: '输出Bucket',
            OUTPUT_KEY_PREFIX: '输出文件前缀',
            OUTPUT_RULES: '输出规则',
            VIDEO_SCREENSHOTS_RULES: '视频截图规则',
            AT_LEAST_ONE_RULE: '输出规则和视频截图规则至少存在一个',
            ADD: '添加',
            MORE_CONFIGURATION: '更多配置',
            YES: '是',
            NO: '否',
            WHETHER_DELETE_ORIGINAL_FILE_AFTER_TRANSCODING: '转码后是否删除原始文件',
            WHETHER_RETAIN_ORIGINAL_PATH_AFTER_TRANSCODING: '转码后是否保留原始路径',
            PERMISSION_SETTINGS: '权限设置',
            USER_GROUP_PERMISSIONS: '用户组权限',
            USER_PERMISSIONS: '用户权限',
            OUTPUT_FILE_NAME_SUFFIX: '输出文件名后缀',
            SCREENSHOT_START_TIME: '截图起始时间点',
            SCREENSHOT_START_TIME_SECOND: '截图起始时间点(秒)',
            SCREENSHOT_INTERVAL: '截图间隔时间',
            SCREENSHOT_INTERVAL_SECOND: '截图间隔时间(秒)',
            SCREENSHOT_MAX_NUMBER: '截图最大数量',
            SCREENSHOT_RESOLUTION: '截图分辨率',
            OK: '确定',
            CANCEL: '取消',
            FORMAT: '格式',
            SLICE_FORMAT: '切片格式',
            TRANSCODING_SUCCESSFUL_CALLBACK_URL: '转码成功回调Url',
            TRANSCODING_FAILED_CALLBACK_URL: '转码失败回调Url',
            FILE_NAME_SUFFIX_CANNOT_EMPTY: '文件名后缀不能为空',
            MASTER_PLAYLIST_CONFIGURATION: 'MasterPlaylist配置',
            MASTER_PLAYLIST_FILE_NAME_SUFFIX: 'MasterPlaylist文件名后缀',
            AUTO_OUTPUT_RULES_DESCRIPTION: '设置自动转码后，输出规则中至少有一项模版输出为TS，且所有HLS切片时长需保持一致，且不能为0',
            ADAPTIVE_EXIST_TS_FORMAT: '设置自适应转码，输出规则中需存在转码模版输出为TS格式的项',
            ADAPTIVE_HLS_SLICE_LENGTH_CONSISTENT: '设置自适应转码，输出规则中HLS切片时长需保持一致',
            ADAPTIVE_HLS_SLICE_LENGTH_CANNOT_BE_0: '设置自适应转码，输出规则中HLS切片时长不能为0',
            SECOND: '秒',
            NEW_PIPELINE: '新建管道',
            PIPELINE_MANAGEMENT: '管道管理',
            PIPELINE_NAME: '管道名称',
            PIPELINE_NAME_INFO: '请输入管道名称',
            PIPELINE_NAME_CANNOT_EMPTY: '管道名称不能为空',
            PIPELINE_NAME_CHAR_NUMBER: '请不要超过40个字符',
            UPDATED_SUCCESSFULLY: '更新成功',
            PIPELINE_ID: '管道ID',
            ACCEPT_JOB_SUCCESS_CALLBACK_URL: '接受任务成功回调的URL',
            ACCEPT_JOB_FAILURE_CALLBACK_URL: '接受任务失败回调的URL',
            ACCEPT_JOB_SUCCESS_CALLBACK_URL_INFO: '请输入接受任务成功回调的URL',
            ACCEPT_JOB_FAILURE_CALLBACK_URL_INFO: '请输入接受任务失败回调的URL',
            ENTER_CORRECT_PIPELINE_NAME: '请输入正确的管道名称',
            STATUS: '状态',
            ACTIONS: '操作',
            NO_DATA: '没有数据',
            SNAPSHOTS_RULES: '视频截图规则',
            OUTPUT_FILE_NAME: '输出文件名',
            MP_NAME_INFO: '文件名不能为空',
            OUTPUT_TABLE_INFO: '输出规则至少存在一个',
            CREATED: '创建成功',
            DELETED: '操作成功',
            PIPE: '管道',
            CREATE_JOB: '创建任务',
            JOB_ID: '转码ID',
            PIPE_ID: '管道ID',
            JOB_TEMPLATE: '转码模版',
            CREATE_TIME: '创建时间',
            OPERATION: '操作',
            JOB_CONF: '主动转码配置',
            JOB_CREATE: '新建转码',
            BASIC_SET: '基础配置',
            JOB_PIPE: '转码管道',
            SRC_FILE: '源文件名',
            SEARCH_INFO: '文件数大于50请使用搜索(前缀匹配)',
            HLS_FILE_NAME: '自适应HLS文件名',
            SRC_FILE_INFO: '请选择输入源文件',
            KEYS_REG: '允许转码的路径规则',
            OUTPUTS: '输出',
            CONTAINER: '输出格式',
            VIDEO: '视频',
            AUDIO: '音频',
            TEMPLATE_NAME_TABLE: '模版名称',
            CONF: '配置',
            WH_UNALTERED: '根据分辨率计算',
            OUTPUTKEY_REQUIRED: '请填写输出文件名',
            SHOTKEY_REQUIRED: '请填写输出文件名后缀',
            OUTPUTEMPLATE_REQUIRED: '请选择转码模版',
            OUTPUTKEY_SUFFIX_REQUIRED: '请输入输出文件名后缀',
            REG_ERROR: '正则表达式错误',
            MP_NAME_ERROR: 'MasterPlaylist文件名后缀无效',
            PIPILINE: '',
            TEMPLATE_DELETED_ERROR: '不能删除正在使用的模版',
            JOB_CANCEL_ERROR: '不能删除正在运行的任务',
            PIPELINE_DELETE_ERROR: '删除失败：该管道正被占用',
            BASE_INFO: '基本信息',
            HLS_REQUIRED: '请填写自适应HLS文件名'
        },
        i: {
            select: {
                placeholder: '请选择',
                noMatch: '无匹配数据'
            },
            table: {
                noDataText: '暂无数据',
                noFilteredDataText: '暂无筛选结果',
                confirmFilter: '筛选',
                resetFilter: '重置',
                clearFilter: '全部'
            },
            datepicker: {
                selectDate: '选择日期',
                selectTime: '选择时间',
                startTime: '开始时间',
                endTime: '结束时间',
                clear: '清空',
                ok: '确定',
                month: '月',
                month1: '1 月',
                month2: '2 月',
                month3: '3 月',
                month4: '4 月',
                month5: '5 月',
                month6: '6 月',
                month7: '7 月',
                month8: '8 月',
                month9: '9 月',
                month10: '10 月',
                month11: '11 月',
                month12: '12 月',
                year: '年',
                weeks: {
                    sun: '日',
                    mon: '一',
                    tue: '二',
                    wed: '三',
                    thu: '四',
                    fri: '五',
                    sat: '六'
                },
                months: {
                    m1: '1月',
                    m2: '2月',
                    m3: '3月',
                    m4: '4月',
                    m5: '5月',
                    m6: '6月',
                    m7: '7月',
                    m8: '8月',
                    m9: '9月',
                    m10: '10月',
                    m11: '11月',
                    m12: '12月'
                }
            },
            transfer: {
                titles: {
                    source: '源列表',
                    target: '目的列表'
                },
                filterPlaceholder: '请输入搜索内容',
                notFoundText: '列表为空'
            },
            modal: {
                okText: '确定',
                cancelText: '取消'
            },
            poptip: {
                okText: '确定',
                cancelText: '取消'
            },
            page: {
                prev: '上一页',
                next: '下一页',
                total: '共',
                item: '条',
                items: '条',
                prev5: '向前 5 页',
                next5: '向后 5 页',
                page: '条/页',
                goto: '跳至',
                p: '页'
            },
            rate: {
                star: '星',
                stars: '星'
            },
            tree: {
                emptyText: '暂无数据'
            }
        }
    }
}
