//  http://jr.baishancloud.com:8090/pages/viewpage.action?pageId=48827543
//  default  transcode config

export const showType = ['MP4', 'FLV', 'M3U8', 'MP3', 'X_COPY']

const init = (
  Type,
  type,
  description,
  audioBitRate,
  videoBitRate,
  resolution,
  width,
  height,
  name,
) => {
  return {
    Type,
    Name:
      resolution === 'auto'
        ? audioBitRate === 'auto'
          ? name
          : `${type}_${audioBitRate}kbps`
        : `${type}_${width}x${height}_${videoBitRate}kbps`,
    template: {
      Description: description,
      Container: type,
      Audio: {
        Codec: type === 'mp3' ? 'mp3' : 'auto',
        CodecOptions: {
          Profile: 'auto',
        },
        SampleRate: 'auto',
        BitRate: audioBitRate,
        Channels: 'auto',
      },
      Video: {
        Codec: type === 'mp3' || !!name ? 'auto' : 'H.264',
        CodecOptions: {
          Profile: 'high',
          Level: '3.1',
        },
        KeyframesMaxDist: '1',
        FixedGOP: false,
        BitRate: videoBitRate,
        FrameRate: 'auto',
        Resolution: 'auto',
        AspectRatio: 'auto',
      },
    },
    auxiliary: {
      videoBitRate: videoBitRate === 'auto' ? 'auto' : 'value',
      audioBitRate: audioBitRate === 'auto' ? 'auto' : 'value',
      audioBitRateValue: parseInt(audioBitRate),
      videoBitRateValue: parseInt(videoBitRate),
      resolution,
      width,
      height,
    },
  }
}

export const templateDefaultLists = () => {
  return [
    // MP4
    init(
      showType[0],
      'mp4',
      'mp4_4K，2160p， 6000kbps，Web和移动设备（iOS，Android）通用',
      '160',
      '6000',
      'value',
      '3840',
      '2160',
    ),
    init(
      showType[0],
      'mp4',
      'mp4_2K，1440p， 3500kbps，Web和移动设备（iOS，Android）通用',
      '160',
      '3500',
      'value',
      '2048',
      '1440',
    ),
    init(
      showType[0],
      'mp4',
      'mp4_全高清，1080p， 3000kbps，Web和移动设备（iOS，Android）通用',
      '160',
      '3000',
      'value',
      '1920',
      '1080',
    ),
    init(
      showType[0],
      'mp4',
      'mp4_高清，720p，1800kbps，Web和移动设备（iOS，Android）通用',
      '128',
      '1800',
      'value',
      '1280',
      '720',
    ),
    init(
      showType[0],
      'mp4',
      'mp4_标清，480p，800kbps，Web和移动设备（iOS，Android）通用',
      '80',
      '800',
      'value',
      '854',
      '480',
    ),
    init(
      showType[0],
      'mp4',
      'mp4_流畅，480p，620kbps，Web和移动设备（iOS，Android）通用',
      '64',
      '620',
      'value',
      '640',
      '480',
    ),
    init(
      showType[0],
      'mp4',
      'mp4_流畅，360p，520kbps，Web和移动设备（iOS，Android）通用',
      '64',
      '520',
      'value',
      '640',
      '360',
    ),
    init(
      showType[0],
      'mp4',
      'mp4_流畅，360p，440kbps，Web和移动设备（iOS，Android）通用',
      '64',
      '440',
      'value',
      '480',
      '360',
    ),
    init(
      showType[0],
      'mp4',
      'mp4_流畅，240p，240kbps，Web和移动设备（iOS，Android）通用',
      '64',
      '240',
      'value',
      '320',
      '240',
    ),
    // FLV
    init(
      showType[1],
      'flv',
      'Flash video_4K，2160p， 6000kbps',
      '160',
      '6000',
      'value',
      '3840',
      '2160',
    ),
    init(
      showType[1],
      'flv',
      'Flash video_2K，1440p， 3500kbps',
      '160',
      '3500',
      'value',
      '2048',
      '1440',
    ),
    init(
      showType[1],
      'flv',
      'Flash video_全高清，1080p， 3000kbps',
      '160',
      '3000',
      'value',
      '1920',
      '1080',
    ),
    init(
      showType[1],
      'flv',
      'Flash video_高清，720p， 1800kbps',
      '128',
      '1800',
      'value',
      '1280',
      '720',
    ),
    init(
      showType[1],
      'flv',
      'Flash videov_标清，480p， 800kbps',
      '80',
      '800',
      'value',
      '854',
      '480',
    ),
    init(
      showType[1],
      'flv',
      'Flash video_流畅，480p，620kbps',
      '64',
      '620',
      'value',
      '640',
      '480',
    ),
    init(
      showType[1],
      'flv',
      'Flash video_流畅，360p ，520kbps',
      '64',
      '520',
      'value',
      '640',
      '360',
    ),
    init(
      showType[1],
      'flv',
      'Flash video_流畅，360p ，440kbps',
      '64',
      '440',
      'value',
      '480',
      '360',
    ),
    init(
      showType[1],
      'flv',
      'Flash video_流畅，240p，240kbps',
      '64',
      '240',
      'value',
      '320',
      '240',
    ),
    // M3U8
    init(
      showType[2],
      'ts',
      'm3u8_4K，2160p，6000kbps，适用Web、iOS设备（iPhone 4以上及iPad）、Android设备（3.0以上）',
      '160',
      '6000',
      'value',
      '3840',
      '2160',
    ),
    init(
      showType[2],
      'ts',
      'm3u8_2K，1440p，3500kbps，适用Web、iOS设备（iPhone 4以上及iPad）、Android设备（3.0以上）',
      '160',
      '3500',
      'value',
      '2048',
      '1440',
    ),
    init(
      showType[2],
      'ts',
      'm3u8_全高清，1080p，3000kbps，适用Web、iOS设备（iPhone 4以上及iPad）、Android设备（3.0以上）',
      '160',
      '3000',
      'value',
      '1920',
      '1080',
    ),
    init(
      showType[2],
      'ts',
      'm3u8_高清，720p，1800kbps，适用Web、iOS设备（iPhone 4以上及iPad）、Android设备（3.0以上）',
      '128',
      '1800',
      'value',
      '1280',
      '720',
    ),
    init(
      showType[2],
      'ts',
      'm3u8_标清，480p ，800kbps，适用Web、iOS设备（iPhone 4以上及iPad）、Android设备（3.0以上）',
      '80',
      '800',
      'value',
      '854',
      '480',
    ),
    init(
      showType[2],
      'ts',
      'm3u8_流畅，480p，620kbps，适用Web、iOS设备（iPhone 4以上及iPad）和Android设备（3.0以上）',
      '64',
      '620',
      'value',
      '640',
      '480',
    ),
    init(
      showType[2],
      'ts',
      'm3u8_流畅，480p，520kbps，适用Web、iOS设备（iPhone 4以上及iPad）和Android设备（3.0以上）',
      '64',
      '520',
      'value',
      '640',
      '360',
    ),
    init(
      showType[2],
      'ts',
      'm3u8_流畅，360p，440kbps，适用Web、iOS设备和Android设备（3.0以上）',
      '64',
      '440',
      'value',
      '480',
      '360',
    ),
    init(
      showType[2],
      'ts',
      'm3u8_流畅，240p，240kbps，适用Web、iOS设备和Android设备（3.0以上）',
      '64',
      '240',
      'value',
      '320',
      '240',
    ),
    // MP3
    init(showType[3], 'mp3', 'mp3，320kbps', '320', 'auto', 'auto', '', ''),
    init(showType[3], 'mp3', 'mp3，192kbps', '192', 'auto', 'auto', '', ''),
    init(showType[3], 'mp3', 'mp3，160kbps', '160', 'auto', 'auto', '', ''),
    init(showType[3], 'mp3', 'mp3，128kbps', '128', 'auto', 'auto', '', ''),
    init(showType[3], 'mp3', 'mp3，64kbps', '64', 'auto', 'auto', '', ''),
    // _COPY
    init(
      showType[4],
      'flv',
      '转FLV格式',
      'auto',
      'auto',
      'auto',
      '',
      '',
      'FLV_COPY',
    ),
    init(
      showType[4],
      'ts',
      'ts切片',
      'auto',
      'auto',
      'auto',
      '',
      '',
      'M3U8_COPY',
    ),
    init(
      showType[4],
      'mp4',
      '转MP4格式',
      'auto',
      'auto',
      'auto',
      '',
      '',
      'MP4_COPY',
    ),
  ]
}
